import { CONTACT_CHANNELS } from '../../data/contact';

export const CONTACT_HIGHLIGHTS = [
  {
    icon: 'pin',
    label: 'Head office',
    value: 'Nairobi, Kenya',
  },
  {
    icon: 'office',
    label: 'Coverage',
    value: 'Africa, Europe, Asia, the Middle East, the Americas, and Oceania',
  },
  {
    icon: 'clock',
    label: 'Response time',
    value: '< 24 Hours',
  },
];

export const CONTACT_OFFICES = [
  {
    id: 'kenya-hq',
    region: 'East Africa',
    country: 'Kenya',
    city: 'Nairobi',
    label: 'Head Office',
    note: 'Primary commercial and coordination desk. Replace the placeholder street details with your exact office address.',
    addressLines: ['Felmex Global Logistics', 'Street address to be added', 'Nairobi, Kenya'],
    phones: [CONTACT_CHANNELS.phoneDisplay],
    email: CONTACT_CHANNELS.emailDisplay,
    hours: 'Mon - Fri / 08:00 - 17:30 EAT',
    directionsHref: '#',
  },
  {
    id: 'tanzania-desk',
    region: 'East Africa',
    country: 'Tanzania',
    city: 'Dar es Salaam',
    label: 'Country Desk',
    note: 'Tanzania office and coordination desk.',
    addressLines: [
      'Rita Tower, 18th Floor',
      'Plot Number 727/11 Makunganya/Simu Street',
      'P.O. Box 31902',
      'Dar es Salaam, Tanzania',
    ],
    phones: ['+254-759-678710'],
    email: CONTACT_CHANNELS.emailDisplay,
    hours: 'Mon - Fri / Local office hours',
    directionsHref: '#',
  },
  {
    id: 'south-sudan-desk',
    region: 'East Africa',
    country: 'South Sudan',
    city: 'Juba',
    label: 'Country Desk',
    note: 'South Sudan office and coordination desk.',
    addressLines: [
      'Hai Kuwait Bilpam Road',
      'Next to North East Building Room 5',
      'Juba, South Sudan',
    ],
    phones: ['Phone number to be added'],
    email: CONTACT_CHANNELS.emailDisplay,
    hours: 'Mon - Fri / Local office hours',
    directionsHref: '#',
  },
  {
    id: 'uganda-desk',
    region: 'East Africa',
    country: 'Uganda',
    city: 'Kampala',
    label: 'Country Desk',
    note: 'Reserved for the Uganda office details once you send the full branch address.',
    addressLines: ['Office address coming next', 'Building and street to be added', 'Kampala, Uganda'],
    phones: ['Phone number to be added'],
    email: CONTACT_CHANNELS.emailDisplay,
    hours: 'Mon - Fri / Local office hours',
    directionsHref: '#',
  },
  {
    id: 'rwanda-desk',
    region: 'East Africa',
    country: 'Rwanda',
    city: 'Kigali',
    label: 'Country Desk',
    note: 'Reserved for the Rwanda branch details and direct local contact line.',
    addressLines: ['Office address coming next', 'Building and street to be added', 'Kigali, Rwanda'],
    phones: ['Phone number to be added'],
    email: CONTACT_CHANNELS.emailDisplay,
    hours: 'Mon - Fri / Local office hours',
    directionsHref: '#',
  },
  {
    id: 'zambia-desk',
    region: 'Southern Africa',
    country: 'Zambia',
    city: 'Lusaka',
    label: 'Country Desk',
    note: 'Add the Zambia office information here when you are ready.',
    addressLines: ['Office address coming next', 'Building and street to be added', 'Lusaka, Zambia'],
    phones: ['Phone number to be added'],
    email: CONTACT_CHANNELS.emailDisplay,
    hours: 'Mon - Fri / Local office hours',
    directionsHref: '#',
  },
  {
    id: 'uae-desk',
    region: 'Middle East',
    country: 'United Arab Emirates',
    city: 'Dubai',
    label: 'Coordination Desk',
    note: 'A good slot for any Gulf coordination desk or partner-facing office details.',
    addressLines: ['Office address coming next', 'Building and street to be added', 'Dubai, UAE'],
    phones: ['Phone number to be added'],
    email: CONTACT_CHANNELS.emailDisplay,
    hours: 'Mon - Fri / Local office hours',
    directionsHref: '#',
  },
];
