export const CLIENT_QUOTES = [
  {
    mark: 'II',
    companyShort: 'Industrial',
    sector: 'Importer',
    image: '/testimonials/testimonial-test-2.webp',
    quote: 'Reliable status updates keep our import desk moving.',
    role: 'Procurement Lead',
    company: 'Varelon Industrial',
    logo: '/testimonials/varelon-industrial.svg',
    logoAlt: 'Varelon Industrial',
    tone: 'is-sky',
  },
  {
    mark: 'CG',
    companyShort: 'Consumer Goods',
    sector: 'Network',
    image: '/testimonials/testimonial-test-3.webp',
    quote: 'Felmex feels like an extension of our operations desk.',
    role: 'Operations Director',
    company: 'Lucera Collective',
    logo: '/testimonials/lucera-collective.svg',
    logoAlt: 'Lucera Collective',
    tone: 'is-amber',
  },
  {
    mark: 'PA',
    companyShort: 'Pharmaceutical',
    sector: 'Distributor',
    image: '/testimonials/testimonial-test-1.webp',
    quote: 'Clear comms. Fewer delays. Stronger results.',
    role: 'Logistics Operations Head',
    company: 'Pharmaceutical Distributor',
    tone: 'is-sage',
  },
];
